# Generated by Django 6.0.7 on 2026-08-27 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0002_alter_bibliotheque_image'),
        ('organisation', '0003_organisation_abonnement'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='bibliotheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='bibliotheque.bibliotheque'),
        ),
    ]
