# Generated by Django 6.0.7 on 2026-08-19 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('adresse', models.TextField()),
                ('telephone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('statut', models.CharField(default='actif', max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/bibliotheque')),
                ('slug', models.SlugField(unique=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='Adherent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bibliotheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.bibliotheque')),
            ],
        ),
    ]
