# Generated by Django 6.0.7 on 2026-08-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliotheque',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/bibliotheque'),
        ),
    ]
