# Generated by Django 6.0.7 on 2026-08-19 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotheque', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bibliotheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.bibliotheque')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('bibliotheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.bibliotheque')),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=255)),
                ('langue', models.CharField(max_length=255)),
                ('pages', models.IntegerField()),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('emprunte', 'Emprunté'), ('endommage', 'Endommagé'), ('non_disponible', 'Non disponible')], default='disponible', max_length=20)),
                ('pdf', models.FileField(upload_to='media/livres')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/livres')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('auteurs', models.ManyToManyField(related_name='livres', to='catalogue.auteur')),
                ('bibliotheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bibliotheque.bibliotheque')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livres', to='catalogue.categorie')),
            ],
        ),
    ]
