# Generated by Django 6.0.7 on 2026-08-21 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livre',
            name='pdf',
        ),
    ]
