# Generated by Django 6.0.7 on 2026-08-19 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bibliotheque', '0001_initial'),
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_emprunt', models.DateTimeField(auto_now_add=True)),
                ('date_limite', models.DateTimeField()),
                ('date_retour', models.DateTimeField(blank=True, null=True)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='bibliotheque.adherent')),
                ('bibliotheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='bibliotheque.bibliotheque')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='catalogue.livre')),
            ],
        ),
    ]
