# Generated by Django 6.0.7 on 2026-08-19 19:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bibliotheque', '0001_initial'),
        ('catalogue', '0001_initial'),
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('date_emprunt', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(max_length=50)),
                ('adherent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='bibliotheque.adherent')),
                ('bibliotheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='bibliotheque.bibliotheque')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='catalogue.livre')),
            ],
        ),
    ]
