# Generated by Django 6.0.7 on 2026-08-23 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0002_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
